config/routes.rb
Rails.application.routes.draw do
  resources :locations
  devise_for :users

  resources :wikis

  resources :charges, only: [:new, :create]

  get 'downgrade' => 'charges#downgrade'

  get 'welcome' => 'welcome#index'

  root to: 'welcome#index'

end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user

  validates :title, length: { minimum: 5 } , presence: true
  validates :body,  length: { minimum: 20 }, presence: true

  #Will_paginate records per page
  #self.per_page = 2

  scope :public_wikis, -> {where(private: false)}
  # scope :private_wikis, -> {where(user_id: current_user.id)}
  scope :ordered, -> {order("created_at DESC")}
  scope :visible_to, -> (user) { user.admin? ? all : where("user_id = ? OR private = ?", user.id, false) }
  # def self.visible_to(user)
  #   user.admin? ? all : (public_wikis + user.wikis).uniq
  # end

  def self.search(query)
    where("%#{query}%")
  end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
      before_action :set_record, except: [:index, :new, :create]
      before_action :authenticate_user!

       def index
         # if current_user.admin?
         #   @wikis = Wiki.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 5)
         # elsif current_user.premium?
         #   #Show all public wikis and owned private wikis
         #   #@wikis = "Not sure how to define collection"
         # else
         #   #current_user.standard?
         #   #Show only public wikis
         #   @wikis = Wiki.where(private: false).order("created_at DESC").paginate(:page => params[:page], :per_page => 5)
         # end

         #@wikis = current_user.wikis.order("created_at DESC").paginate(:page => params[:page], :per_page => 5)
         #@wikis = Wiki.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 5)
         #@wikiPrivateCount = Wiki.where(private: true).count.to_s
         @wikis = Wiki.visible_to(current_user).ordered.paginate(:page => params[:page], :per_page => 5)
         @personalWikiCount = current_user.wikis.count.to_s
         @PersonalWikiPrivateCount = current_user.wikis.where(private: true).count.to_s

         if params[:search]
               @wikis = Wiki.search(params[:search]).order("created_at DESC")
            else
               @wikis = Wiki.all.order('created_at DESC')
            end
         end
       end

       def show
         # Render the show view
       end

       def create
         @wiki = current_user.wikis.build(wiki_params)

         if @wiki.save
           flash[:notice] = "saved"
           redirect_to wikis_path
         else
           flash[:error] = @wiki.errors.full_messages.to_sentence
           render :new
         end
       end

       def edit
         # Render the edit view
         # @ wiki is set in the private set_record method and executed by the before_action:
         #@wiki = Wiki.find(params[:id])
         authorize @wiki
       end

       def update
         # @item = Item.find(params[:id]) - not necessary because of before_action to set item
          @wiki.assign_attributes(wiki_params)
          authorize @wiki
          if @wiki.save
            flash[:notice] = "Wiki was updated."
           redirect_to wikis_path
          else
            flash[:error] = @wiki.errors.full_messages.to_sentence
            render :edit
          end
       end

       def new
         @wiki = Wiki.new
       end

       def destroy
          @wiki = Wiki.find(params[:id])

          if @wiki.destroy
            flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
            redirect_to action: :index
          else
            flash[:error] = "There was an error deleting the wiki."
            render :show
          end
       end

       private

       def set_record
         @wiki = Wiki.find(params[:id])
         # begin
         #   @wiki = current_user.wikis.find(params[:id])
         # rescue
         #   @wiki = nil
         # end
       end

       def wiki_params
         params.require(:wiki).permit(:title, :body, :private)
       end
   

app/views/wikis/_form.html.erb
<!--Used in Edit and New Views-->
<%= form_for @wiki do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, autofocus: true,   class: 'form-control', placeholder: "Enter wiki name" %>
    <%= f.label :body %>
    <%= f.text_area :body,                      class: 'form-control', placeholder: "Enter wiki content", size: "25x6" %>
    <p>**bold** _italic_ `code` >quote * - bullet list"</p>

    <% if current_user.admin? || current_user.premium? %>
      <div class="form-group">
        <%= f.check_box :private %> Private wiki
      </div>
    <% end %>

  </div>
  <%= f.submit "Save", class: 'btn btn-success' %>
  <%= link_to "Cancel", wikis_path, class: 'btn btn-success' %>
  <% if current_user.admin? || current_user.premium? %>
    <%= button_to "Manage Collaborators", "", data: { confirm: "Are you sure you want to manage collaborators?" }, class: 'btn btn-success', method: :get %>
  <% end %>
<% end %>

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>
 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for Wiki:</p>
     <ul>
       <li>Make is short.</li>
       <li>Keep it interesting.</li>
     </ul>
   </div>
   <div class="col-md-8">
    <%= render "form" %>
   </div>
</div>

app/views/wikis/index.html.erb
<!--<h5><%#= @wikis.count %> <%#= "Wiki".pluralize(@wikis.count) %> total. (<%#= @wikiPrivateCount %> are private.)</h5>-->
<h5><%= @personalWikiCount %> <%= "Wiki".pluralize(@personalWikiCount.to_i) %> owned by you. (<%= @PersonalWikiPrivateCount %> are private.)</h5>
 <table class="table table-striped">
   <tr>
    <th>TITLE</th>
     <th>BODY</th>
     <th>AUTHOR</th>
     <th>PRIVATE</th>
     <th>DELETE</th>
   </tr>
   <% @wikis.each do |wiki| %>
     <tr>
      <td>
         <%= link_to wiki.title, wiki %>
      </td>
      <td>
         <% if wiki.body %>
           <%#Only show the first max_size characters %>
           <% max_size = 50 %>
           <%= wiki.body.length > max_size ? markdown(wiki.body[0,max_size] + "...") : markdown(wiki.body)  %>
         <% end %>
      </td>
        <td>
         <%= User.find(wiki.user_id).name %>
      </td>
      <td>
         <% if wiki.private %>
           <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
         <% end %>
      </td>
      <td align="left" class="action">
         <%= link_to "", wiki, method: :delete, class: 'glyphicon glyphicon-remove', data: { confirm: 'Are you sure you want to delete this Wiki?' }  %>
      </td>
     </tr>
   <% end %>
 </table>
<%= link_to "New wiki ", new_wiki_path, class: 'btn btn-success' %><br /><br />
<div><%= page_entries_info @wikis, renderer: BootstrapPagination::Rails %></div>
<%= will_paginate @wikis, renderer: BootstrapPagination::Rails %>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>
 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for wikis:</p>
     <ul>
       <li>Make it short.</li>
       <li>Use action verbs.</li>
     </ul>
   </div>
   <div class="col-md-8">
     <%= render "form" %>
   </div>
</div>

app/views/wikis/show.html.erb
<% if @wiki %>
<div>
  <H1><%= @wiki.title %></H1>
  <p><%= markdown(@wiki.body) %></p>
  <p><%= "Private:  #{@wiki.private}" %></p>


</div>
<% else %>
  <p>I couldn't find that wiki in your list.</p>
<% end %>
<% if policy(@wiki).edit? %>
  <%= link_to "Edit Wiki", edit_wiki_path, class: 'btn btn-success' %>
<% end %>
<%= link_to "Wiki List", wikis_path, class: 'btn btn-success' %>
<%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this Wiki?' } %>