config/routes.rb
Rails.application.routes.draw do
  resources :locations
  devise_for :users

  resources :wikis

  resources :charges, only: [:new, :create]

  get 'downgrade' => 'charges#downgrade'

  get 'welcome' => 'welcome#index'

  root to: 'welcome#index'

end

app/views/layouts/application.haml
!!! 5
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie9" lang="en"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!-->

%html{:lang => "en"} <!--<![endif]-->
%head
  %meta{:charset => "utf-8"}
  %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}

  %title= content_for?(:title) ? yield(:title) : "Blocipedia"
  = javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.5/marked.js"
  = stylesheet_link_tag    "application"
  = javascript_include_tag "vendor/custom.modernizr"
  = csrf_meta_tags


%body
  = render 'layouts/topbar'

  .row
    = render 'layouts/messages'
    = yield


= javascript_include_tag "application"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Botanopedia</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
    </head>

    <body class="<%= @body_class %>">
        <div class="container-pills">
            <% if user_signed_in? %>
                Signed in as: <strong> <%= "#{current_user.name} - #{current_user.email} (#{current_user.role})" %></strong>
                    <ul class="nav nav-pills pull-right">
                        <li class="active"><%= link_to 'Edit profile', edit_user_registration_path, :class => '' %> </li>
                        <li class="active"><%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => '' %> </li>
                        <li class="active"><%= link_to "Wikis", wikis_path, class: '' %> </li>
                    </ul>
            <% else %>
            <ul class="nav nav-pills pull-right">
               <li class="btn btn-info"><%= link_to "Sign Up", new_user_registration_path, :class => 'pull-right'  %> </li>
               <li class="btn btn-info"><%= link_to "Sign In", new_user_session_path, :class => 'pull-right'  %> </li>
            </ul>
            <% end %>
            <div class="search_bar">
              <%= form_tag(wikis_path, :method => "get", id: "search-form") do %>
                <%= text_field_tag :search, params[:search], placeholder: "Search Wikis" %>
                <%= submit_tag "Search", :name => nil %>
            </div>
            <% end %>

      <div class="flash">
            <% if flash[:notice] %>
                <div class="alert alert-success">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                    <%= flash[:notice] %>
                </div>
            <% elsif flash[:error] %>
                <div class="alert alert-danger">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                    <%= flash[:error] %>
                </div>
            <% elsif flash[:alert] %>
                <div class="alert alert-warning">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                    <%= flash[:alert] %>
               </div>
            <% end %>
        </div>

        <%= yield %>
        </div>
    </body>
</html>

app/views/layouts/application.html.haml
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= @body_class %>">
<div class="container">
   <% if user_signed_in? %>
     Signed in as: <strong> <%= "#{current_user.name} - #{current_user.email} (#{current_user.role})" %></strong>
     <ul class="nav nav-pills pull-right">
       <li class="active"><%= link_to 'Edit profile', edit_user_registration_path, :class => '' %> </li>
       <li class="active"><%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => '' %> </li>
       <li class="active"><%= link_to "Wikis", wikis_path, class: '' %> </li>
     </ul>
   <% else %>
     <ul class="nav nav-pills pull-right">
       <li class="active"><%= link_to "Sign Up", new_user_registration_path, :class => 'pull-right'  %> </li>
       <li class="active"><%= link_to "Sign In", new_user_session_path, :class => 'pull-right'  %> </li>
     </ul>
   <% end %>

   <hr>
   <div class="flash">
     <% if flash[:notice] %>
       <div class="alert alert-success">
         <button type="button" class="close" data-dismiss="alert">&times;</button>
         <%= flash[:notice] %>
       </div>
     <% elsif flash[:error] %>
       <div class="alert alert-danger">
         <button type="button" class="close" data-dismiss="alert">&times;</button>
         <%= flash[:error] %>
       </div>
     <% elsif flash[:alert] %>
       <div class="alert alert-warning">
         <button type="button" class="close" data-dismiss="alert">&times;</button>
         <%= flash[:alert] %>
       </div>
     <% end %>
  </div>
  <%= yield %>
</body>
</div>
</html>